-- ─────────────────────────────────────────────────────────────
-- E-Signature schema — ROSTER native signing workflow
-- 2026-04-29
--
-- Tables:
--   signing_requests   — one row per signing flow (the contract + recipient + status)
--   signing_audit_log  — every action against a request (created, sent, viewed, signed, declined, downloaded)
--
-- Trust model:
--   • Requester's user_id is recorded; only the requester can read / list / cancel their own.
--   • Recipient access is via signed token (HMAC-SHA-256, short-lived) — no auth required.
--   • Audit log is owned by requester (RLS scoped); admin client used for token-based inserts.
-- ─────────────────────────────────────────────────────────────

-- ── signing_requests ────────────────────────────────────────
create table if not exists public.signing_requests (
  id uuid primary key default gen_random_uuid(),

  -- Who is sending the contract for signature
  requester_user_id uuid not null references auth.users(id) on delete cascade,
  requester_name text not null,
  requester_email text not null,

  -- Who needs to sign
  recipient_email text not null,
  recipient_name text not null,

  -- The contract being signed
  contract_type text not null,                      -- e.g. "Management Agreement", "Booking Agency", "Sync License"
  contract_title text not null,                     -- human-readable title
  contract_html text not null,                      -- snapshot of the contract HTML at the time of sending (immutable)
  contract_metadata jsonb default '{}'::jsonb,      -- arbitrary key/value (territory, term, fee, etc.)

  -- Token for recipient access (short-lived, signed, NOT a uuid — generated by HMAC)
  token text not null unique,
  expires_at timestamptz not null,

  -- Lifecycle
  status text not null default 'sent'
    check (status in ('draft','sent','viewed','signed','declined','expired','cancelled')),
  sent_at timestamptz default now(),
  first_viewed_at timestamptz,
  signed_at timestamptz,
  declined_at timestamptz,
  decline_reason text,

  -- Captured signature data (when signed)
  signature_image_data text,            -- base64 PNG of the drawn signature
  signature_typed_name text,            -- typed full legal name for verification
  signer_ip text,                        -- IP address at time of sign
  signer_user_agent text,                -- browser/device at time of sign

  -- Final signed PDF (storage path)
  signed_pdf_storage_path text,

  -- Timestamps
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_signing_requests_user on public.signing_requests(requester_user_id);
create index if not exists idx_signing_requests_token on public.signing_requests(token);
create index if not exists idx_signing_requests_status on public.signing_requests(status);
create index if not exists idx_signing_requests_recipient on public.signing_requests(recipient_email);

-- ── signing_audit_log ──────────────────────────────────────
create table if not exists public.signing_audit_log (
  id uuid primary key default gen_random_uuid(),
  signing_request_id uuid not null references public.signing_requests(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,    -- null when triggered by recipient (not authenticated)
  action text not null
    check (action in ('created','sent','viewed','signed','declined','expired','cancelled','downloaded','reminder_sent')),
  ip text,
  user_agent text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_signing_audit_request on public.signing_audit_log(signing_request_id);
create index if not exists idx_signing_audit_created on public.signing_audit_log(created_at desc);

-- ── updated_at trigger ─────────────────────────────────────
create or replace function public.set_signing_request_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_signing_requests_updated_at on public.signing_requests;
create trigger trg_signing_requests_updated_at
  before update on public.signing_requests
  for each row execute function public.set_signing_request_updated_at();

-- ── RLS ────────────────────────────────────────────────────
alter table public.signing_requests enable row level security;
alter table public.signing_audit_log enable row level security;

-- signing_requests policies
drop policy if exists "signing_requests_select_own" on public.signing_requests;
create policy "signing_requests_select_own"
  on public.signing_requests
  for select
  to authenticated
  using (auth.uid() = requester_user_id);

drop policy if exists "signing_requests_insert_own" on public.signing_requests;
create policy "signing_requests_insert_own"
  on public.signing_requests
  for insert
  to authenticated
  with check (auth.uid() = requester_user_id);

drop policy if exists "signing_requests_update_own" on public.signing_requests;
create policy "signing_requests_update_own"
  on public.signing_requests
  for update
  to authenticated
  using (auth.uid() = requester_user_id)
  with check (auth.uid() = requester_user_id);

drop policy if exists "signing_requests_delete_own" on public.signing_requests;
create policy "signing_requests_delete_own"
  on public.signing_requests
  for delete
  to authenticated
  using (auth.uid() = requester_user_id);

-- signing_audit_log policies
-- Requester can read audit log entries for their own requests.
drop policy if exists "signing_audit_select_own" on public.signing_audit_log;
create policy "signing_audit_select_own"
  on public.signing_audit_log
  for select
  to authenticated
  using (
    exists (
      select 1 from public.signing_requests
      where signing_requests.id = signing_audit_log.signing_request_id
        and signing_requests.requester_user_id = auth.uid()
    )
  );

-- Inserts to audit log are only via service-role (admin client) since recipient
-- actions (viewed/signed/declined) come from non-authenticated browser sessions.
-- No INSERT policy for authenticated role is required.

-- ── Storage bucket for signed PDFs ─────────────────────────
-- (Run separately via Supabase dashboard or storage admin API:)
-- 1. Create private bucket "signed-contracts" with 10 MB cap
-- 2. RLS policy: select / insert / update / delete scoped to requester_user_id
--    folder convention {user_id}/{signing_request_id}/signed.pdf

-- Storage policies (SQL form — run after bucket exists)
-- drop policy if exists "signed_contracts_select_own" on storage.objects;
-- create policy "signed_contracts_select_own"
--   on storage.objects for select to authenticated
--   using (bucket_id = 'signed-contracts' and (storage.foldername(name))[1] = auth.uid()::text);
--
-- drop policy if exists "signed_contracts_insert_own" on storage.objects;
-- create policy "signed_contracts_insert_own"
--   on storage.objects for insert to authenticated
--   with check (bucket_id = 'signed-contracts' and (storage.foldername(name))[1] = auth.uid()::text);
