// ─────────────────────────────────────────────────────────────────────────────
// ROSTER — Algeria Exclusive Artist Management Agreement
// Governing Law: People's Democratic Republic of Algeria
// Law No. 03-05 of July 19, 2003 on Copyright and Related Rights
// Currency: DZD · Rights Body: ONDA · Tax Authority: DGI · 2026 Edition
// ─────────────────────────────────────────────────────────────────────────────

export interface SubClause {
  ref: string;
  text: string;
  sub?: { ref: string; text: string }[];
}

export interface Clause {
  id: string;
  title: string;
  intro?: string;
  subclauses: SubClause[];
}

export interface ScheduleItem {
  ref: string;
  text: string;
}

export const ALGERIA_CLAUSES: Clause[] = [
  {
    id: "1",
    title: "Definitions and Interpretation",
    subclauses: [
      {
        ref: "1.1",
        text: "Interpretation",
        sub: [
          { ref: "", text: "Unless the context clearly indicates otherwise, words importing the singular shall include the plural and vice versa, words importing natural persons shall include juristic persons and vice versa, and words importing one gender shall include the other genders." },
        ],
      },
      {
        ref: "1.2",
        text: "Key Definitions",
        sub: [
          { ref: "Acts", text: "Law No. 03-05 of July 19, 2003 on Copyright and Related Rights, as amended, and all regulations promulgated thereunder, and includes all applicable performers' protection legislation in Algeria governing the rights of performing artists and producers of sound recordings." },
          { ref: "Artist", text: "The performing artist, recording artist, and vocalist resident in Algeria named as a party to this Agreement." },
          { ref: "Artist's Services", text: "All activities, whether direct or indirect, relating to the Artist's abilities, skills, and potential to produce, publish, record, programme, perform, sing, act, dance, model, endorse, merchandise, broadcast, author, and otherwise exploit the Artist's personality rights, creative abilities, performance capacity, and output in all media and formats, whether now known or hereafter devised." },
          { ref: "Gross Income", text: "All income generated by the exploitation of the Artist's Services, excluding any amounts paid by a purchaser in respect of production, transport, or other verifiable third-party costs incurred to deliver the Artist's Services, and excluding TVA or equivalent indirect tax in Algeria." },
          { ref: "Management Fee", text: "The fee payable to Management as set out in the First Schedule." },
          { ref: "Net Income", text: "The income accruing to the Artist after deduction of the Management Fee in accordance with the First Schedule, prior to deduction of any tax payable by the Artist." },
          { ref: "New Media", text: "All digital, internet, and electronic formats, domains, media, and carriers, including social media and networks, chat platforms, streaming services, websites, and all other digital community, corporate, and organisational networks, including without limitation YouTube, Spotify, Boomplay, Audiomack, Apple Music, Instagram, TikTok, X (formerly Twitter), Facebook, and all equivalent or successor platforms." },
          { ref: "ONDA", text: "The Office National des Droits d'Auteur et des Droits Voisins, the performing rights and neighbouring rights organisation with jurisdiction in Algeria, responsible for collecting and distributing performance, composition, and neighbouring rights royalties." },
          { ref: "DGI", text: "The Direction Générale des Impôts, the tax authority responsible for administering income tax, TVA, and other fiscal obligations in Algeria." },
          { ref: "Personality Rights", text: "All rights in and to the name, image, likeness, voice, depiction, characterisation, and stage name of the Artist." },
          { ref: "Territory", text: "The world." },
          { ref: "Term", text: "The period specified in clause 10 of this Agreement." },
        ],
      },
      {
        ref: "1.3",
        text: "Headings",
        sub: [
          { ref: "", text: "The headings in this Agreement are inserted for convenience only and shall not be considered in the interpretation or construction hereof." },
        ],
      },
    ],
  },
  {
    id: "2",
    title: "Grant of Rights",
    subclauses: [
      {
        ref: "2.1",
        text: "Exclusive Grant",
        sub: [
          { ref: "2.1.1", text: "The Artist hereby grants to Management, for the Term and throughout the Territory, the exclusive right to manage and represent the Artist as detailed herein, and to advise, guide, and direct the Artist in respect of all aspects relating to the Artist's Services." },
          { ref: "2.1.2", text: "To advise the Artist on market conditions and orientation, including business operating structure and knowledge; technical and production issues; repertoire and creative direction; trends and market intelligence; public profile and image; networking and industry relationships; lifestyle considerations; best practice in the Algeria music industry; market communication and New Media strategy; customer and audience orientation; and collaborations, features, and co-productions." },
          { ref: "2.1.3", text: "To organise all logistics in respect of clauses 2.1.1 and 2.1.2 above." },
        ],
      },
      {
        ref: "2.2",
        text: "Scope of Management Services",
        sub: [
          { ref: "2.2.1", text: "Marketing, selling, agenting, sourcing, quoting, negotiating, and securing performance contracts for the Artist's live performances, including shows, concerts, and festival appearances." },
          { ref: "2.2.2", text: "Marketing, selling, agenting, sourcing, quoting, negotiating, and securing appearance contracts for the Artist's personal appearances, media appearances, and promotional engagements." },
          { ref: "2.2.3", text: "Marketing, selling, agenting, sourcing, quoting, negotiating, and securing personality rights contracts for commercial and non-commercial engagements involving the Artist's Personality Rights in all media, formats, and domains." },
          { ref: "2.2.4", text: "Marketing, selling, agenting, sourcing, quoting, negotiating, and securing New Media and social network contracts and relationships for commercial and non-commercial engagements involving the Artist's Personality Rights." },
          { ref: "2.2.5", text: "Implementing all contracts referred to in clauses 2.2.1 to 2.2.4 (inclusive), including the collection of all payments thereunder." },
          { ref: "2.2.6", text: "Liaising, negotiating, and coordinating relationships and agreements with the Artist's record label, music publisher, and digital distributor." },
          { ref: "2.2.7", text: "Researching and facilitating all travel logistics in respect of the Artist's engagements (provided that Management shall not be responsible for the Artist's transportation between the Artist's personal residence and any local departure point)." },
          { ref: "2.2.8", text: "Ensuring, insofar as is reasonably practicable, that technical equipment and production requirements are met in accordance with the Artist's production and technical rider." },
          { ref: "2.2.9", text: "Promoting and publicising the Artist's name and talents to purchasers, promoters, brands, and industry stakeholders in Algeria and internationally." },
          { ref: "2.2.10", text: "Providing the Artist with complete itinerary details prior to any travel for engagements." },
          { ref: "2.2.11", text: "Conducting all business correspondence on the Artist's behalf in relation to the services hereunder." },
          { ref: "2.2.12", text: "Cooperating with the Artist's auditors, business advisors, and legal counsel as and when required." },
          { ref: "2.2.13", text: "Liaising with relevant authorities in respect of visa and work permit requirements for cross-border travel and engagements, and ensuring such requirements are met and cleared for all performances hereunder." },
          { ref: "2.2.14", text: "Maintaining adequate bookkeeping, accounting, and audit systems in compliance with applicable laws in respect of all receipts collected on the Artist's behalf hereunder." },
          { ref: "2.2.15", text: "Collecting all receipts in respect of all contracts issued hereunder, accounting to the Artist monthly in arrears." },
          { ref: "2.2.16", text: "Liaising and directing the preparation of the Artist's accounts receivable and accounts payable, in conjunction with auditors, and maintaining proper books and accounts in accordance with DGI regulations." },
          { ref: "2.2.17", text: "Liaising with the Artist's record label and music publisher in respect of any obligations arising therefrom." },
          { ref: "2.2.18", text: "Managing and conducting all communications in respect of the Artist's Services, and liaising with any third-party queries or claims in respect thereof." },
          { ref: "2.2.19", text: "Facilitating and coordinating all logistics and arrangements with the Artist in respect of the Artist's professional commitments." },
          { ref: "2.2.20", text: "Liaising with the Artist's business affairs advisors in respect of all agreements involving the Artist's copyrights and other intellectual property rights." },
        ],
      },
      {
        ref: "2.3",
        text: "Licence of Personality Rights",
        sub: [
          { ref: "2.3.1", text: "The Artist hereby agrees and irrevocably consents, during the Term only, to Management's exclusive right to use (in connection with the marketing, promotion, and publicity of the Artist and the Artist's Services) and to licence (for commercial and non-commercial purposes) the Artist's Personality Rights." },
          { ref: "2.3.2", text: "The Artist, having conceived and created their professional name, is the sole and exclusive owner thereof as at the Effective Date, whether registered as a trade mark or not, and Management's rights in respect of the Artist's Personality Rights are solely as a licensee during the Term and do not constitute any assignment of the Artist's ownership of their stage name or associated trade marks." },
        ],
      },
    ],
  },
  {
    id: "3",
    title: "Limitations of the Grant of Rights",
    subclauses: [
      {
        ref: "3.1",
        text: "Prior Written Approval Required",
        sub: [
          { ref: "3.1.1", text: "Use of the Artist's Personality Rights for product and service endorsements, associations, and relationships." },
          { ref: "3.1.2", text: "Notwithstanding Management's liaison and negotiation responsibilities with the Artist's music publisher, publishing rights in and to musical, dramatic, and literary works authored and created by the Artist during the Term are subject to a separate publishing agreement." },
          { ref: "3.1.3", text: "Notwithstanding Management's liaison and negotiation responsibilities with the Artist's record label, sound recording rights in and to the Artist's performances on any sound recording made during the Term are subject to a separate artist agreement." },
        ],
      },
      {
        ref: "3.2",
        text: "Excluded Matters",
        sub: [
          { ref: "3.2.1", text: "Management shall have no rights to represent the Artist in respect of the Artist's personal banking, medical, private insurance matters, or obligations to DGI (which remain the Artist's direct personal responsibility)." },
        ],
      },
    ],
  },
  {
    id: "4",
    title: "Warranties and Representations",
    subclauses: [
      {
        ref: "4.1",
        text: "Artist's Warranties",
        sub: [
          { ref: "4.1.1", text: "The Artist has the full right, power, and authority to enter into this Agreement and to grant to Management the rights herein set forth, and shall not derogate from such grant during the Term." },
          { ref: "4.1.2", text: "There is no suit, action, claim, or other legal or administrative proceeding pending or threatened that might directly or indirectly affect any services to be rendered hereunder or impair Management's ability to exercise the rights granted hereunder." },
          { ref: "4.1.3", text: "All provisions hereunder affecting the Artist shall be binding on any company or business entity owned, controlled, or affiliated with the Artist, in whole or in part, directly or indirectly." },
          { ref: "4.1.4", text: "The Artist shall not, during the Term, offer any of the exclusive rights granted to Management hereunder to any third party in any manner that excludes, prejudices, or deprives Management thereof, whether intentionally or otherwise." },
          { ref: "4.1.5", text: "The Artist shall fulfil all third-party obligations detailed, organised, or facilitated by Management hereunder, including all scheduled performances, appearances, and media commitments." },
          { ref: "4.1.6", text: "Mutual trust between the Parties is essential to the productivity, success, and sustainability of this Agreement." },
          { ref: "4.1.7", text: "The Artist shall not unreasonably withhold any consent reasonably requested by Management in furtherance of the Artist's career." },
          { ref: "4.1.8", text: "All performances by the Artist and grants of rights to Management hereunder are subject to the provisions of the Acts." },
        ],
      },
      {
        ref: "4.2",
        text: "Management's Warranties",
        sub: [
          { ref: "4.2.1", text: "Management has the full right, power, and authority to enter into this Agreement and to perform the obligations herein set forth, and shall not derogate therefrom." },
          { ref: "4.2.2", text: "There is no suit, action, claim, or other legal or administrative proceeding pending or threatened that might directly or indirectly affect any services to be rendered hereunder or impair the Artist's rights hereunder." },
          { ref: "4.2.3", text: "All provisions hereunder affecting Management shall be binding on any company or business entity owned, controlled, or affiliated with Management, in whole or in part, directly or indirectly." },
          { ref: "4.2.4", text: "Management shall maintain, during the Term, proper books of account in accordance with generally accepted accounting principles applicable in Algeria and in compliance with all applicable laws and DGI regulations." },
          { ref: "4.2.5", text: "Mutual trust between the Parties is essential to the productivity, success, and sustainability of this Agreement." },
          { ref: "4.2.6", text: "Management shall not unreasonably withhold any consent reasonably requested by the Artist." },
          { ref: "4.2.7", text: "The works of the Artist are published pursuant to a separate publishing agreement, and all related incomes accruing to the Artist as author, composer, and arranger shall form part of Gross Income hereunder." },
          { ref: "4.2.8", text: "The works of the Artist are recorded pursuant to a separate artist recording agreement, and all related incomes accruing to the Artist as a performer on recordings shall form part of Gross Income hereunder." },
          { ref: "4.2.9", text: "All performances by the Artist and grants of rights hereunder are subject to the provisions of the Acts." },
        ],
      },
    ],
  },
  {
    id: "5",
    title: "Artist and Management Relationship",
    subclauses: [
      { ref: "5.1", text: "Nothing in this Agreement shall constitute or be deemed to constitute a partnership between the Parties. The Artist, in performing any services hereunder, shall be deemed an independent contractor, and nothing herein shall constitute the Artist as an agent or employee of Management, nor shall it constitute Management as a partner or employee of the Artist." },
    ],
  },
  {
    id: "6",
    title: "Management's Undertaking",
    subclauses: [
      {
        ref: "6.1",
        text: "Management undertakes to use all reasonable endeavours in respect of the Artist's Services for the benefit of the Artist and the Artist's career, including but not limited to",
        sub: [
          { ref: "6.1.1", text: "Marketing and promotion of the Artist's name, recordings, and live performances." },
          { ref: "6.1.2", text: "Valuation, negotiation, and settlement of performance and appearance fees at market-competitive rates." },
          { ref: "6.1.3", text: "Planning and implementation of ongoing promotional and marketing activities on the Artist's behalf with buyers, music distributors, promoters, and similar entities." },
          { ref: "6.1.4", text: "The broadening of the Artist's profile in the Algeria market and regionally, with specific emphasis on New Media and social networking opportunities; sponsorship, association, and endorsement opportunities with brands active in Algeria; growth of the Artist's New Media following and engagement metrics; collaborations, features, and co-productions with other artists in Algeria and regionally; personality rights licensing across all categories; jingle, advertising, and synchronisation opportunities; merchandise design, production, and distribution opportunities; and songwriting, production, and programming opportunities." },
          { ref: "6.1.5", text: "The facilitation, with the Artist's record company and distributor, of in-store promotions, store visits, and personal appearances at music industry retail outlets, radio stations, media platforms, and similar venues." },
          { ref: "6.1.6", text: "All other marketing activities the general purpose of which is to further the Artist's career and maximise the commercial value of the Artist's Services." },
        ],
      },
    ],
  },
  {
    id: "7",
    title: "Artist's Personality Rights",
    subclauses: [
      { ref: "7.1", text: "The Artist hereby agrees and irrevocably consents, during the Term only, to Management's exclusive right to use (in connection with the marketing, promotion, and publicity of the Artist and the Artist's Services) and to licence (for commercial and non-commercial purposes) the Artist's Personality Rights, including the exclusive licensing thereof for all uses envisaged by this Agreement. Such use shall be at no cost or liability to Management and is essential for the operation of this Agreement. This consent includes use in New Media and the internet, and is granted to Management by way of exclusive licence." },
      { ref: "7.2", text: "Notwithstanding anything to the contrary herein, the Artist, having conceived and created their professional name, is the sole and exclusive owner thereof as at the Effective Date, whether registered as a trade mark or not, and Management's rights in respect of the Artist's Personality Rights are solely as a licensee during the Term and do not constitute any assignment of the Artist's ownership of their stage name or associated trade marks." },
    ],
  },
  {
    id: "8",
    title: "Sale and Use of the Artist's Services Outside Algeria",
    subclauses: [
      { ref: "8.1", text: "The Parties agree that regional and international opportunities for the deployment of the Artist's Services, although not easily secured, are vital to the growth of the Artist's career and are a priority for Management." },
      { ref: "8.2", text: "Management shall, in the ordinary course of business, address and, where commercially viable, secure all demand for the Artist's Services in international markets." },
      { ref: "8.3", text: "Depending on the Artist's professional growth, the Parties may agree during the Term that it is prudent to engage third-party booking agencies, agents, or sub-managers on a territorial basis to book performances and appearances in specific markets outside Algeria. Any such appointment requires the Artist's prior written consent." },
      { ref: "8.4", text: "If appropriate, prudent, and reasonable, Management shall, after consultation with the Artist, determine how best to accommodate any such third-party territorial representation costs. In the event Management appoints a dedicated territorial booking agent for the Artist, the fees payable to such agent shall, like TVA, be excluded from 'Gross Income' hereunder." },
    ],
  },
  {
    id: "9",
    title: "Artist Career Growth and the Impact of Growth",
    subclauses: [
      { ref: "9.1", text: "The Parties acknowledge and agree that the primary purpose of this Agreement is the sustained growth of the Artist's career, and that success in achieving this purpose may alter the commercial circumstances existing at the Effective Date." },
      {
        ref: "9.2",
        text: "Growth of the Artist's career hereunder is understood in three dimensions",
        sub: [
          { ref: "9.2.1", text: "Public stature and market relevance — locally, nationally, regionally across Africa, and internationally." },
          { ref: "9.2.2", text: "Professionalism and artistic development as a performing artist." },
          { ref: "9.2.3", text: "Income generated from the Artist's Services." },
        ],
      },
      { ref: "9.3", text: "Growth in market relevance is determined primarily by market demand for the Artist (driven by the Artist's work, recordings, and live performances) and secondarily by the Artist's New Media following and engagement. The Artist's personal attention to New Media is critical, as decisions by advertisers, brands, and event promoters to engage the Artist are often directly influenced by such metrics." },
      { ref: "9.4", text: "Growth in professionalism is observable through positive media presence, punctuality, responsiveness, stage performance quality, and the Artist's personal development. The Artist is encouraged to invest time in professional development." },
      { ref: "9.5", text: "Upon the Gross Income accruing to the Artist first exceeding the threshold set out in the First Schedule per month on a consistent basis for three (3) consecutive months, the Artist shall, in consultation with Management and Management's advisors, review and, if appropriate, corporatise the Artist's commercial affairs to ensure statutory compliance and tax efficiency in Algeria as required by DGI." },
    ],
  },
  {
    id: "10",
    title: "Term",
    subclauses: [
      { ref: "10.1", text: "The Term of this Agreement shall be four (4) years commencing on the Effective Date, subject to the option in clause 10.2 below." },
      { ref: "10.2", text: "Management shall have the option to renew this Agreement upon expiry of the initial four (4) year period for a further period of four (4) years, exercisable by written notice delivered to the Artist not less than sixty (60) days prior to the expiry of the initial period. Such option may only be exercised if Management has fulfilled all material obligations hereunder during the preceding period." },
      { ref: "10.3", text: "If the Parties wish to continue their professional relationship after the option period (if exercised), they shall negotiate in good faith, having regard to the commercial circumstances prevailing at that time and the income generated for the Artist during the preceding period." },
    ],
  },
  {
    id: "11",
    title: "Accounts and Payments",
    subclauses: [
      { ref: "11.1", text: "In respect of the exploitation of the Artist's Services by Management and Management's exclusive right to collect income generated thereby, Management shall be entitled to the fees set out in the First Schedule hereto, which shall become due and payable only as provided therein and hereinbelow." },
      { ref: "11.2", text: "Management shall maintain proper books and records of account in respect of all marketing and sales of the Artist's Services hereunder, in accordance with applicable Algeria accounting standards and DGI requirements." },
      { ref: "11.3", text: "The rates in the First Schedule shall be calculated on one hundred percent (100%) of the Gross Income received by or credited to Management (or the Artist, as applicable) directly and identifiably attributable to the Artist in the Territory, after deduction only of: (i) TVA and other similar indirect taxes required to be deducted in any part of the Territory; and (ii) technical and production costs paid directly to third parties and not recoverable from the purchaser." },
      { ref: "11.4", text: "Management shall pay the Artist, in accordance with the First Schedule, the Artist's share of Gross Income actually received by Management, subject to: (i) prior recoupment by Management of any monies advanced, loaned, or otherwise provided to the Artist, subject to applicable credit legislation in Algeria; (ii) settlement of any tax obligations payable by the Artist; (iii) deduction of any actual transport, travel, communication, and entertainment costs not covered by third parties and pre-approved by the Artist; and (iv) monthly payment to the Artist in arrears of all Net Income." },
      { ref: "11.5", text: "Any income received by Management as a deposit for a future performance or engagement by the Artist shall be held in trust until such performance or engagement is completed, and shall not constitute Gross Income hereunder until the relevant obligation is fulfilled." },
      { ref: "11.6", text: "All statements and accounts rendered by Management to the Artist shall be binding on the Artist and not subject to objection unless specific written objection, stating the basis thereof in reasonable detail, is given to Management within three (3) years from the date of rendering." },
      { ref: "11.7", text: "The Artist shall have the right, at the Artist's expense, to engage independent registered auditors, attorneys, or business advisors to examine Management's books and records relating to the marketing and sales of the Artist's Services hereunder, during reasonable business hours and on reasonable prior written notice, but not more than once per calendar year." },
      { ref: "11.8", text: "If such examination establishes an underpayment to the Artist exceeding the threshold set out in the First Schedule for the period examined, Management shall pay the reasonable and direct professional costs of the examination (excluding travel, accommodation, and subsistence), not exceeding the amount specified in the First Schedule, which amount shall not be considered in computing the underpayment itself." },
      { ref: "11.9", text: "For the avoidance of doubt, Management shall be entitled, during the Term, to collect one hundred percent (100%) of income in respect of the Artist's Services or any exploitation thereof, subject to clauses 4.2.7 and 4.2.8 (in which cases the Artist receives income directly from the music publisher or record label as applicable)." },
    ],
  },
  {
    id: "12",
    title: "Post-Term Commissions (Sunset Clause)",
    subclauses: [
      { ref: "12.1", text: "Notwithstanding any termination or expiry of this Agreement, Management shall be entitled to receive commissions on all Gross Income attributable to the Artist's Services derived from or in connection with any contracts, engagements, agreements, recordings, compositions, works, projects, or other exploits that were substantially negotiated, secured, initiated, or entered into during the Term (collectively, 'During-Term Exploits')." },
      {
        ref: "12.2",
        text: "Such post-Term commissions shall be calculated at the following reduced rates of the Management Fee otherwise applicable hereunder",
        sub: [
          { ref: "12.2.1", text: "For the first year following termination or expiry: 20% (twenty per cent)." },
          { ref: "12.2.2", text: "For the second year following termination or expiry: 15% (fifteen per cent)." },
          { ref: "12.2.3", text: "For the third year following termination or expiry: 10% (ten per cent)." },
          { ref: "12.2.4", text: "For the fourth year following termination or expiry: 5% (five per cent)." },
          { ref: "12.2.5", text: "For the fifth year following termination or expiry: 5% (five per cent)." },
          { ref: "12.2.6", text: "Thereafter: 0% (zero per cent)." },
        ],
      },
      {
        ref: "12.3",
        text: "For the avoidance of doubt",
        sub: [
          { ref: "12.3.1", text: "Post-Term commissions shall be computed, deducted, and paid in the same manner as the Management Fee during the Term, mutatis mutandis." },
          { ref: "12.3.2", text: "The Artist shall procure that all third parties paying Gross Income from During-Term Exploits pay such amounts directly to Management (or as Management may direct) to facilitate deduction of post-Term commissions." },
          { ref: "12.3.3", text: "The Artist's accounting, reporting, and audit obligations hereunder shall continue to apply in respect of Gross Income subject to post-Term commissions for so long as such commissions remain payable." },
          { ref: "12.3.4", text: "This clause shall survive termination or expiry of this Agreement and shall be binding on the Artist and any successor, assignee, or affiliated entity of the Artist." },
        ],
      },
    ],
  },
  {
    id: "13",
    title: "Media",
    subclauses: [
      { ref: "13.1", text: "The Parties agree that media generally, and New Media specifically, are critical for the Artist's communication with fans and industry stakeholders in Algeria and internationally, and are central to the growth of the Artist's Services." },
      { ref: "13.2", text: "The Parties further agree that media interactions carry risks, as public statements may be used adversely against the Artist or Management." },
      { ref: "13.3", text: "Given the ongoing nature of media interactions relating to the Artist and the Artist's Services, the Artist undertakes, to the best of their ability, to: (i) understand and apply the principles of effective media engagement, including responding directly and constructively to questions; (ii) remain informed on current affairs in the Algeria music industry to respond appropriately and credibly; (iii) present professionally for face-to-face, broadcast, or live digital interactions; (iv) be considerate, respectful, and courteous to interviewers and media representatives; and (v) be punctual for all scheduled media engagements and communicate any delays to Management immediately." },
      { ref: "13.4", text: "All significant media engagements, interviews, and public statements that may materially affect the Artist's commercial relationships shall be coordinated with Management in advance where practicable." },
    ],
  },
  {
    id: "14",
    title: "Tax",
    subclauses: [
      { ref: "14.1", text: "The Parties shall comply with all DGI (Direction Générale des Impôts) regulations concerning the Artist's income tax and any other deductions required under the laws of the People's Democratic Republic of Algeria." },
      { ref: "14.2", text: "The Parties agree to remain compliant at all times during the Term with all DGI regulations concerning the Artist's Net Income, including making requisite deductions, timely payments to DGI, filing all required forms and returns, and maintaining accurate records." },
      { ref: "14.3", text: "The Artist acknowledges that, as a public figure, any breach of DGI regulations or outstanding tax liability may have material and adverse consequences for the Artist's professional reputation and career in Algeria, notwithstanding the terms of this Agreement." },
      { ref: "14.4", text: "TVA (Taxe sur la Valeur Ajoutée) is administered by DGI at the current statutory rate." },
    ],
  },
  {
    id: "15",
    title: "Notices",
    subclauses: [
      { ref: "15.1", text: "Any notice required or permitted hereunder shall be in writing and may be served: (i) by prepaid registered or recorded delivery post to the address of the receiving Party as set out above or any other address notified in accordance with this clause, deemed served seven (7) days after posting; (ii) by hand delivery to such address, deemed served on the date of delivery and acknowledgement; or (iii) by email to such email address as set out above, with a read-receipt requested, deemed served on the date of transmission if no delivery failure notification is received within 24 hours." },
      { ref: "15.2", text: "Either Party may change their contact address or email address during the Term by written notice to the other in accordance with this clause." },
    ],
  },
  {
    id: "16",
    title: "Force Majeure",
    subclauses: [
      { ref: "16.1", text: "If a Party's material performance hereunder is substantially delayed, rendered impossible, or impracticable due to any act of God, fire, earthquake, flood, strike, civil commotion, pandemic, epidemic, governmental acts or restrictions, actions of any relevant performers' association affecting the Artist, Management, or the entertainment industry in Algeria generally, thereby materially hampering Management's exploitation of rights hereunder, the affected Party may, upon prompt written notice to the other, suspend its obligations for the duration thereof." },
      { ref: "16.2", text: "The Term shall be extended by a period equal to any such suspension. Any suspension arising from interference with Management's normal business operations (as opposed to the music industry generally in Algeria) shall not exceed six (6) months in aggregate, after which either Party may terminate this Agreement on thirty (30) days' written notice without further liability for the period of suspension." },
    ],
  },
  {
    id: "17",
    title: "Governing Law",
    subclauses: [
      { ref: "17.1", text: "This Agreement shall be governed by and construed in accordance with the laws of the People's Democratic Republic of Algeria applicable to contracts executed and to be performed wholly therein." },
      { ref: "17.2", text: "The Parties agree that any dispute arising from or in connection with this Agreement shall first be submitted to good-faith negotiation for a period of thirty (30) days. Failing resolution, the dispute shall be submitted to binding arbitration before the Centre Algérien de Médiation et d'Arbitrage (CAMA) in Algiers, whose award shall be final and binding." },
      { ref: "17.3", text: "All terms relating to music herein shall have the meanings ascribed thereto in the Acts." },
    ],
  },
  {
    id: "18",
    title: "Indemnity",
    subclauses: [
      { ref: "18.1", text: "The Artist shall indemnify and hold harmless Management from and against any demands, losses, claims, proceedings, damages, costs, and expenses (including reasonable legal fees) arising from any claim inconsistent with, or due to any breach of, the Artist's representations, warranties, grants, undertakings, covenants, or agreements hereunder. Management shall not compromise or settle any third-party claim touching on the Artist's rights without the Artist's prior written consent, which shall not be unreasonably withheld or delayed." },
      { ref: "18.2", text: "Management shall indemnify and hold harmless the Artist from and against any demands, losses, claims, proceedings, damages, costs, and expenses (including reasonable legal fees) arising from any claim inconsistent with, or due to any breach of, Management's representations, warranties, grants, undertakings, or agreements hereunder. The Artist shall not compromise or settle any third-party claim without Management's prior written consent, which shall not be unreasonably withheld or delayed." },
    ],
  },
  {
    id: "19",
    title: "Assignment",
    subclauses: [
      { ref: "19.1", text: "The Artist shall not assign, encumber, transfer, or otherwise dispose of any rights hereunder (including copyright, performance, personality, and related rights) to any third party during the Term without Management's prior written consent." },
      { ref: "19.2", text: "Management may assign its rights hereunder to any entity that controls, is controlled by, or is under common control with Management, upon reasonable prior written notice to the Artist, provided such assignment does not diminish the quality or standard of services due to the Artist. Management may not assign this Agreement to an unrelated third party without the Artist's prior written consent." },
    ],
  },
  {
    id: "20",
    title: "Termination and Breach",
    subclauses: [
      { ref: "20.1", text: "Either Party may forthwith terminate the Term by written notice to the other if the other Party enters into liquidation (other than voluntary liquidation for the purpose of reconstruction or reorganisation), compounds with its creditors, or has a trustee, administrator, or receiver appointed over all or a substantial part of its assets, which appointment is not discharged within thirty (30) days." },
      { ref: "20.2", text: "If Management materially defaults in the performance of any material provision hereof (including accounting, payment, and reporting obligations) and such default (if capable of remedy) continues for thirty (30) days after receipt of written notice from the Artist specifying the default in reasonable detail, the Artist may terminate the Term by further written notice to Management." },
      { ref: "20.3", text: "If the Artist materially defaults in the performance of any material provision hereof (including obligations to appear, perform, fulfil media commitments, and not to undermine Management's exclusive rights) and such default (if capable of remedy) continues for thirty (30) days after receipt of written notice from Management specifying the default in reasonable detail, Management may terminate the Term by further written notice to the Artist." },
      { ref: "20.4", text: "Termination hereunder shall not affect, impede, or release either Party from rights and obligations that have already accrued, nor shall it cancel or terminate any assignments of rights made during the Term. All post-termination obligations — including the Post-Term Commission provisions in clause 12 and payment of accrued fees — shall survive termination and remain fully enforceable." },
    ],
  },
  {
    id: "21",
    title: "Miscellaneous",
    subclauses: [
      { ref: "21.1", text: "A waiver by either Party of any term or condition hereof in any instance shall not be deemed a waiver of that term for any future instance. All rights, remedies, undertakings, and obligations herein are cumulative and none shall limit any other right or remedy available to either Party." },
      { ref: "21.2", text: "This Agreement constitutes the entire agreement between the Parties and supersedes all prior agreements, representations, negotiations, and understandings, whether written or oral, concerning the subject matter hereof. No modification or variation hereof shall be effective unless in writing and signed by both Parties." },
      { ref: "21.3", text: "Nothing herein shall constitute a partnership, joint venture, or employment relationship between the Parties, and neither Party shall be bound by any act or omission of the other except as expressly provided in this Agreement." },
      { ref: "21.4", text: "If any provision hereof or the application thereof to any particular circumstance is adjudged invalid, unlawful, or unenforceable by a court of competent jurisdiction or an arbitral tribunal, such judgment shall not affect the remainder of this Agreement, which shall continue in full force and effect as if the invalid provision had not been included." },
      { ref: "21.5", text: "This Agreement may be executed in counterparts, including by valid electronic signature, each of which shall constitute an original, and all counterparts together shall constitute one and the same agreement." },
    ],
  },
];

export const ALGERIA_SCHEDULE: ScheduleItem[] = [
  {
    ref: "A. Support to the Artist by Management",
    text: "Management shall supply the following to the Artist, at no cost to the Artist, during the Term:",
  },
  {
    ref: "A.1",
    text: "A dedicated professional email address for the Artist's business communications during the Term.",
  },
  {
    ref: "A.2",
    text: "Secure digital access (via HTTPS platform or equivalent) for the Artist to view itineraries, accounting statements, income records, and other documents periodically.",
  },
  {
    ref: "A.3",
    text: "Monthly accounting statements itemising all Gross Income collected, Management Fee deducted, recoverable costs deducted, and Net Income paid to the Artist.",
  },
  {
    ref: "B. Management Fees",
    text: "During the Term, Management shall be entitled to deduct from Gross Income collected from the exploitation of the Artist's Services hereunder the following:",
  },
  {
    ref: "B.1",
    text: "A Management Fee of 20% (twenty per cent) of Gross Income arising from all live performance, appearance, endorsement, sponsorship, sync licensing, and personality rights engagements.",
  },
  {
    ref: "B.2",
    text: "A Management Fee of 20% (twenty per cent) of the Artist's record label income, received directly by the Artist.",
  },
  {
    ref: "B.3",
    text: "A Management Fee of 20% (twenty per cent) of the Artist's music publishing income (including performance royalties from ONDA, mechanical royalties from the applicable mechanical society, neighbouring rights from ONDA, and sync fees), received directly by the Artist.",
  },
  {
    ref: "B.4",
    text: "Any monies due to Management from the Artist, the receipt of which has been acknowledged in writing by the Artist or which are properly due under this Agreement.",
  },
  {
    ref: "B.5",
    text: "Any legal or business affairs costs associated with third-party disputes and licence or other agreements generating income for the Artist and Management, prior to payment to either Party, as pre-approved by the Artist.",
  },
  {
    ref: "B.6 — Escalating Fee Thresholds",
    text: "If combined monthly receipts exceed the First Threshold agreed in writing by the Parties, the Management Fee for income above that threshold shall be 22.5%. If combined monthly receipts exceed the Second Threshold, the Management Fee for income above that threshold shall be 25%. If combined monthly receipts exceed the Third Threshold, the Management Fee shall be 30%. Threshold amounts shall be agreed in writing by the Parties and inserted into this Schedule prior to execution.",
  },
];

export const ALGERIA_META = {
  flag: "🇩🇿",
  country: "Algeria",
  currency: "DZD",
  governingLaw: "the People's Democratic Republic of Algeria",
  lawReference: "Law No. 03-05 of July 19, 2003 on Copyright and Related Rights",
  taxAuthority: "DGI (Direction Générale des Impôts)",
  taxType: "TVA (Taxe sur la Valeur Ajoutée)",
  rightsBody: "ONDA (Office National des Droits d'Auteur et des Droits Voisins)",
  businessReg: "CNRC (Centre National du Registre du Commerce)",
  arbitration: "Centre Algérien de Médiation et d'Arbitrage (CAMA), Algiers",
  lawyerNote: "qualified Algerian entertainment attorney",
  clauseCount: "21 clauses + First Schedule",
  signatoryIdLabel: "Numéro d'Identification Fiscale (NIF)",
  signatoryRegLabel: "CNRC Registration No.",
};
