/**
 * Brand / sponsorship / influencer contract clause libraries.
 */
export interface Clause { num: string; title: string; text: string; }

export const INFLUENCER = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Engagement", text: "Brand engages Creator to produce and post the deliverables described in Schedule A on Creator's social platforms in support of Brand's marketing campaign. Creator agrees to deliver to the standard, format, schedule and platforms set out in Schedule A." },
  { num: "2", title: "Deliverables", text: "Deliverables are listed in Schedule A and shall include for each post: (i) platform; (ii) format (single post / carousel / Reel / TikTok / Story / YouTube Shorts / long-form); (iii) caption / script approval; (iv) hashtags + handles; (v) call to action; (vi) post date / window; (vii) usage rights." },
  { num: "3", title: "Fee & Payment", text: "Brand shall pay Creator the fee specified in Schedule A. Payment terms: 50% on full execution; 50% on completion of all deliverables and submission of post-campaign report. Invoices are paid within fourteen (14) days. Where the fee includes ad-spend boost, that amount is held in trust and applied to the agreed boost; unspent boost is refunded." },
  { num: "4", title: "Approvals", text: "Creator shall submit drafts of all sponsored content to Brand for written approval at least seventy-two (72) hours before the agreed post date. Brand shall provide approval, change requests, or rejection within twenty-four (24) hours. Brand's approval shall not be unreasonably withheld; where Brand fails to respond within the window, draft is deemed approved." },
  { num: "5", title: "Disclosure & Compliance", text: "Creator shall comply with all applicable advertising disclosure rules including FTC (US), ASA (UK), ARASA (South Africa), APCON (Nigeria), and Meta / TikTok / YouTube paid-partnership disclosure features. Posts shall include #ad or #sponsored or use the platform's branded-content tag. Failure to disclose constitutes a material breach." },
  { num: "6", title: "Usage Rights", text: "Creator grants Brand a non-exclusive, royalty-free licence to share, repost and re-use the deliverables on Brand's owned channels and in paid media, for the territory and term in Schedule A. Where Brand wishes to use the deliverables outside that scope (e.g. broadcast TV, OOH), additional fee is negotiated." },
  { num: "7", title: "Exclusivity", text: "Where Schedule A specifies category exclusivity, Creator shall not post promotional content for any directly competing product / service for the duration in Schedule A. Category and competitor list are defined in Schedule A; ambiguous overlaps are resolved in good faith." },
  { num: "8", title: "Boost / Allowlist", text: "Where Brand wishes to boost the post or run it as a paid ad on Creator's handle, Creator grants Brand allowlist permission for the duration and platforms in Schedule A. Creator retains the right to withdraw allowlist on thirty (30) days' written notice if Brand uses it inconsistently with the agreed creative." },
  { num: "9", title: "Performance & Reporting", text: "Creator shall provide a post-campaign report within fourteen (14) days of the final post including: impressions, reach, engagement, click-through, video views, audience demographics. Where Brand requires verified performance via a third-party reporting platform (e.g. CreatorIQ, Tagger), Creator shall co-operate." },
  { num: "10", title: "Warranties", text: "Creator warrants: (i) original creative work; (ii) no third-party rights infringed; (iii) compliance with platform community guidelines; (iv) accurate disclosure; (v) verified followers (no purchased / fraudulent followers). Creator indemnifies Brand against direct claims arising from breach of these warranties up to a cap equal to the fee paid." },
  { num: "11", title: "Termination", text: "Either party may terminate on seven (7) days' notice for material breach not cured. Brand may terminate immediately where Creator publishes content that brings Brand into reputational disrepute, in which case fees paid for completed work are retained by Creator and unbilled fees are forfeited." },
  { num: "12", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const BRAND_ENDORSEMENT = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Endorsement", text: "Artist agrees to endorse Brand's product / service ('Product') for the territory and term set out in Schedule A. The endorsement covers: appearance in advertising, use of Artist's name, image, likeness, and biographical information in marketing material; participation in agreed promotional activities; and (where stated) inclusion of the Product in Artist's content / live performances." },
  { num: "2", title: "Fee & Royalties", text: "Brand shall pay Artist the endorsement fee specified in Schedule A. Where Schedule A includes a royalty on Product sales attributable to the endorsement, Brand shall account quarterly with sales data. Endorsement fees are typically structured as: a fixed retainer + per-deliverable fee + (where applicable) royalty on co-branded SKU." },
  { num: "3", title: "Term & Territory", text: "The Term and Territory are set out in Schedule A. Renewal terms (if any) are set out in Schedule A. Where the endorsement uses Artist's name in the Product (e.g. signature line), the licence may extend beyond the Term subject to a sell-through period and final inventory cap." },
  { num: "4", title: "Exclusivity", text: "Where Schedule A specifies category exclusivity, Artist shall not endorse a directly competing product / service in the same Territory for the Term. Category and direct-competitor list are defined in Schedule A. Casual on-camera or organic appearance with a competitor's product (e.g. wearing a different brand's sneakers) shall not constitute breach unless used in advertising." },
  { num: "5", title: "Approvals & Creative Control", text: "Brand shall submit all uses of Artist's name, image, likeness or voice for prior written approval. Approvals not unreasonably withheld and shall be granted or denied within the window in Schedule A. Where Artist objects to a creative direction in good faith, Brand shall not proceed without further consultation." },
  { num: "6", title: "Morality Clause", text: "Each party may terminate where the other engages in conduct that brings the other into material reputational disrepute, including but not limited to: criminal conviction; public conduct inconsistent with the brand values; or public association with conduct that would reasonably damage the other party's commercial standing. Termination requires thirty (30) days' written notice and a reasonable opportunity to cure." },
  { num: "7", title: "Performance Obligations", text: "Artist shall: (i) appear on the agreed dates / events; (ii) speak positively about the Product in interviews and on owned channels; (iii) decline to disparage the Product or Brand publicly; (iv) refer reasonable enquiries about the Product to Brand. Artist's existing creative output is not bound by the endorsement (e.g. Artist's lyrics, public commentary on unrelated topics)." },
  { num: "8", title: "Product Provision", text: "Brand shall provide Artist with reasonable quantities of the Product for personal use and for promotional content during the Term. Provision is part of the consideration; quantities are set out in Schedule A." },
  { num: "9", title: "Reporting", text: "Brand shall provide Artist with quarterly campaign performance summaries including impressions, reach, engagement, sales attributable, retail placement. Artist may audit campaign reporting once per Term on thirty (30) days' notice." },
  { num: "10", title: "Warranties", text: "Brand warrants the Product is fit for purpose, complies with applicable laws, and that no third-party rights bar Brand from entering this endorsement. Artist warrants the right to grant the endorsement, no exclusive deal bars the engagement, and accurate biographical information. Mutual indemnities up to a cap equal to fees paid." },
  { num: "11", title: "Termination", text: "Either party may terminate for material breach not cured within thirty (30) days. On termination by Brand without cause, Artist is entitled to fees due for the period elapsed plus the unbilled portion to the next milestone, capped at six (6) months. On termination by Artist for Brand's breach, Artist is entitled to the full Term fee unless mitigated." },
  { num: "12", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const AMBASSADOR = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Appointment", text: "Brand appoints Artist as its Ambassador for the Term and Territory in Schedule A. The Ambassadorship is a long-term commitment combining endorsement, content production, event appearances, and (where stated) ambassador-led product / collaboration releases. Ambassador commits to representing Brand consistently across the Term." },
  { num: "2", title: "Annual Fee & Tier Structure", text: "Brand shall pay Artist the annual ambassador fee specified in Schedule A, paid quarterly in advance. The fee includes a base ambassador retainer + per-deliverable fee. Where Schedule A includes performance bonuses (sales-based, growth-based, milestone-based), bonuses are accounted at the cadence specified." },
  { num: "3", title: "Deliverables", text: "Per quarter, Ambassador shall deliver: (i) the social posts specified in Schedule A; (ii) attendance at the agreed events; (iii) participation in the agreed brand campaigns; (iv) interviews / press where reasonably requested; (v) (where stated) input on co-branded product / collaboration." },
  { num: "4", title: "Co-Branded Releases", text: "Where Schedule A includes a co-branded product or collaboration release, ambassador's name and likeness on the product, the revenue share or royalty, and the creative approval process are set out in Schedule A. Co-branded SKUs survive Term termination subject to a sell-through period." },
  { num: "5", title: "Exclusivity", text: "Ambassador shall not endorse directly competing products / services in Territory for the Term. The competitor list is defined in Schedule A. The ambassadorship is generally exclusive within category for the Term." },
  { num: "6", title: "Brand Guidelines", text: "Ambassador shall observe Brand's marketing guidelines (logo placement, brand voice, prohibited associations) when posting, on the basis that Brand provides written guidelines on signature. Ambassador retains creative discretion within those guidelines." },
  { num: "7", title: "Performance Bonus", text: "Where Schedule A includes performance bonuses tied to sales, follower growth, or campaign KPIs, Brand shall account quarterly with verified data. Disputes over performance data may be subject to third-party audit at the disputing party's cost." },
  { num: "8", title: "Renewal / Right of First Refusal", text: "Where Schedule A includes a Right of First Refusal (ROFR) on renewal, Brand shall offer renewal terms not less than ninety (90) days before Term expiry. Ambassador has thirty (30) days to accept or counter; if rejected, Ambassador may consider competing offers but shall not finalise with a competitor for ten (10) days post-rejection." },
  { num: "9", title: "Morality & Reputation", text: "Mirror of clause 6 in Brand Endorsement: each party may terminate for conduct bringing the other into material reputational disrepute, with thirty (30) days' written notice and cure opportunity." },
  { num: "10", title: "Termination", text: "Either party may terminate for material breach not cured within thirty (30) days. Brand may terminate without cause on ninety (90) days' notice; Ambassador is entitled to the unbilled balance of the current contract year. Ambassador may terminate for cause without notice on Brand's failure to pay fees after fourteen (14) days." },
  { num: "11", title: "Post-Term", text: "Following Term expiry: (i) Brand shall not use ambassador likeness in new advertising save where licensed; (ii) Co-branded SKUs continue under sell-through; (iii) Ambassador retains the right to use Ambassador title in biographical contexts (e.g. \"former ambassador for [Brand]\")." },
  { num: "12", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];
