/**
 * Publishing module contract clause libraries.
 * Each function takes the country's governing law + lawyer note and returns
 * the locale-adjusted clause set.
 */
export interface Clause { num: string; title: string; text: string; }

export const PUBLISHING_ADMIN = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Appointment", text: "Songwriter appoints Administrator on a non-exclusive (or exclusive, where stated in Schedule A) basis to administer the Compositions identified in Schedule B for the Term and Territory in Schedule A. Administrator's role is administrative — Songwriter retains full ownership of the underlying copyright in each Composition." },
  { num: "2", title: "Scope of Administration", text: "Administrator shall: (i) register the Compositions with the appropriate performing rights organisations (PROs), mechanical rights organisations (MROs) and digital service providers; (ii) collect performance, mechanical, sync and other publishing income worldwide; (iii) issue licences within Schedule A's pre-approval thresholds; (iv) account to Songwriter on the cadence in Schedule A; (v) audit licensees on Songwriter's reasonable request and at Administrator's cost where adjustments exceed three per cent (3%)." },
  { num: "3", title: "Sync Pre-Approval", text: "Administrator shall not commit any Composition to a synchronisation licence above the pre-approval threshold in Schedule A without Songwriter's prior written consent (typical industry pre-approvals: ad / brand / political content always require consent regardless of fee). All sync licences shall comply with the MFN policy in Schedule A where one is set." },
  { num: "4", title: "Administration Fee", text: "Administrator shall retain the percentage specified in Schedule A as its administration fee, applied to gross publishing income collected, before remittance of the balance to Songwriter. Industry-standard administration deals range from 10–25%; the rate in Schedule A is the entire consideration save for direct out-of-pocket expenses pre-approved by Songwriter." },
  { num: "5", title: "Term & Territory", text: `This Agreement runs for the Term in Schedule A. The Territory is World unless otherwise stated. Either party may terminate at the end of the Term on ninety (90) days' written notice. Compositions licensed during the Term remain commissionable to Administrator on a sunset basis for twelve (12) months thereafter.` },
  { num: "6", title: "Songwriter's Reservation of Rights", text: "Songwriter retains: (i) ownership of the copyright in each Composition; (ii) the right to write, record, perform and publish; (iii) the writer share of all PRO income (which is collected and paid by the writer's own PRO direct, not through Administrator); (iv) reversion rights set out in Schedule A." },
  { num: "7", title: "Pipeline Income", text: "Income earned during the Term but received after termination shall flow to Administrator under the same terms for the period stated in Schedule A (typically 6 months for streaming / digital, 24 months for sync / film and TV). Thereafter, Songwriter shall be paid direct or through Songwriter's nominated successor administrator." },
  { num: "8", title: "Accounting & Audit", text: "Administrator shall account to Songwriter on a quarterly (or semi-annual, where stated in Schedule A) basis, with statement detail showing source, period, gross, deductions and net. Songwriter may audit Administrator's records on thirty (30) days' written notice once per year, at Songwriter's cost; provided that where the audit identifies underpayment of more than three per cent (3%), Administrator shall bear the cost." },
  { num: "9", title: "Warranties & Indemnities", text: "Songwriter warrants ownership and the right to grant administration. Administrator warrants the right to administer in the Territory. Each party indemnifies the other against direct claims arising from breach of these warranties up to a cap equal to fees paid under this Agreement." },
  { num: "10", title: "Termination for Cause", text: "Either party may terminate immediately on written notice for material breach not cured within thirty (30) days. On termination for cause by Songwriter, Administrator shall transfer all registrations, statements and licence files to Songwriter or Songwriter's nominee within thirty (30) days." },
  { num: "11", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Disputes shall be referred to mediation and, failing resolution, to arbitration. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const CO_PUBLISHING = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Co-Publishing Structure", text: "Songwriter and Publisher enter into a co-publishing arrangement on the Compositions in Schedule B. Songwriter assigns to Publisher the percentage of the publisher's share specified in Schedule A (typically 50%), retaining the writer share in full. The split structure is: Writer share to Songwriter (typically 50% of total); Publisher share split between Publisher and Songwriter as set out in Schedule A (typically 25/25 of total)." },
  { num: "2", title: "Term & Territory", text: `Term and Territory are set out in Schedule A. World territory is standard. The Term may include a delivery commitment (e.g. minimum number of Compositions per year) — see Schedule A.` },
  { num: "3", title: "Advance & Recoupment", text: "Publisher shall pay Songwriter the advance specified in Schedule A, recoupable from Songwriter's share of co-publishing income. Advances are not recoupable from Songwriter's writer share of PRO income, which is paid direct to Songwriter by the relevant PRO." },
  { num: "4", title: "Administration", text: "Publisher shall administer the Compositions worldwide for the Term, including registration with PROs and MROs, licensing, collection, accounting, anti-piracy enforcement, and protection of copyright. Sync pre-approval thresholds in Schedule A apply." },
  { num: "5", title: "Songwriter's Obligations", text: "Songwriter shall: (i) deliver Compositions to a commercial standard within the timeframe in Schedule A; (ii) execute split sheets for every Composition before commercial release; (iii) provide accurate metadata (ISWC, PRO affiliation, writer shares); (iv) not transfer publishing rights in any Composition to a third party during the Term; (v) participate in reasonable promotional activity for the catalogue." },
  { num: "6", title: "Reversion", text: "After the Term, ownership of the publisher share of the Compositions shall remain with Publisher, save where Schedule A grants a reversion right (typically 7-10 years post-Term, conditional on full advance recoupment). Reversion is to be effected by deed of assignment registered with all relevant PROs and MROs." },
  { num: "7", title: "Audit", text: "Songwriter may audit Publisher's books once per year on thirty (30) days' written notice, at Songwriter's cost. Underpayment of more than three per cent (3%) shifts audit cost to Publisher." },
  { num: "8", title: "Sync, Brand & Political Use", text: "Publisher shall not licence any Composition for any: (i) advertisement; (ii) political campaign; (iii) trailer for an unapproved Production; or (iv) use Songwriter has flagged as off-limits in writing — without Songwriter's prior written consent. Sync income above the threshold in Schedule A also requires consent." },
  { num: "9", title: "Warranties", text: "Songwriter warrants originality, ownership, and that no third-party rights are infringed save where samples / interpolations are disclosed in writing. Publisher warrants its right to enter the Agreement. Mutual indemnities up to a cap equal to amounts received under this Agreement." },
  { num: "10", title: "Termination for Cause", text: "Either party may terminate for material breach not cured within thirty (30) days. Bankruptcy, insolvency, or business rescue is grounds for immediate termination by the non-defaulting party." },
  { num: "11", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Disputes shall be referred to mediation and, failing resolution, to arbitration. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const STAFF_WRITER = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Engagement", text: "Publisher engages Songwriter as a staff writer on the terms set out in this Agreement. Songwriter shall write and deliver Compositions to Publisher on an exclusive basis for the Term and Territory in Schedule A. The number of Compositions to be delivered annually is the Minimum Delivery Commitment in Schedule A." },
  { num: "2", title: "Exclusivity", text: "During the Term, Songwriter shall write exclusively for Publisher within the Territory. Co-writes with third parties are permitted subject to: (i) Publisher's prior written consent; (ii) Publisher receiving Songwriter's pro-rata share of the publisher share of the resulting Composition; (iii) the third-party co-writer's split being documented before commercial release." },
  { num: "3", title: "Ownership of Compositions", text: "Publisher shall own one hundred per cent (100%) of the publisher share of every Composition written during the Term. Songwriter retains the writer share. Where Schedule A specifies a co-publishing percentage, Songwriter retains a share of the publisher share as stated. Ownership vests in Publisher upon creation as a commissioned work." },
  { num: "4", title: "Weekly / Monthly Salary", text: "Publisher shall pay Songwriter the salary or weekly draw specified in Schedule A, recoupable from Songwriter's writer-share earnings (and co-publishing share where applicable). Salary is paid on the cadence in Schedule A and continues regardless of monthly delivery, save during periods of force majeure or material breach." },
  { num: "5", title: "Minimum Delivery Commitment", text: "Songwriter shall deliver the Minimum Delivery Commitment in each year of the Term. A Composition counts toward delivery only when fully written, demoed to a commercial standard, and accepted by Publisher (acceptance is not unreasonably withheld). Failure to meet delivery may extend the Term by the period of shortfall." },
  { num: "6", title: "Demo Costs", text: "Publisher shall pay reasonable demo recording costs for each Composition. Such costs are recoupable from Songwriter's earnings under this Agreement on the same basis as the salary advance." },
  { num: "7", title: "Pitching & Cuts", text: "Publisher shall use reasonable efforts to pitch Compositions to artists, labels, sync supervisors and other licensees. Songwriter is entitled to information on cuts secured. Cut bonuses (where applicable) are set out in Schedule A." },
  { num: "8", title: "Reversion", text: "Compositions written during the Term remain in Publisher's catalogue post-Term. Schedule A may grant a reversion (typically 7-10 years post-Term, conditional on full recoupment)." },
  { num: "9", title: "Warranties", text: "Songwriter warrants exclusivity, originality, and that no Composition will infringe third-party rights save samples / interpolations disclosed in writing. Mutual indemnities up to a cap equal to advances paid." },
  { num: "10", title: "Termination", text: "Either party may terminate for material breach not cured within thirty (30) days. Publisher may terminate immediately for failure to deliver after extended cure. Songwriter may terminate immediately for failure to pay salary after fourteen (14) days' notice." },
  { num: "11", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const SINGLE_SONG_ASSIGNMENT = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Assignment", text: "Songwriter hereby irrevocably assigns to Publisher one hundred per cent (100%) of the publisher share of the Composition identified in Schedule A, throughout the world, for the full term of copyright (or the Term in Schedule A, where shorter). Songwriter retains the writer share." },
  { num: "2", title: "Consideration", text: "Publisher shall pay Songwriter the consideration specified in Schedule A, in full and final settlement of the assignment. Where Schedule A specifies a recoupable advance, the advance is recouped from Songwriter's writer share of all sources of income from the Composition collected by Publisher." },
  { num: "3", title: "Licensing", text: "Publisher shall have full right to license the Composition for any use whatsoever, including but not limited to recording, sync, public performance, mechanical reproduction, lyric reprint, sheet music, and digital exploitation. Sync pre-approval thresholds in Schedule A apply." },
  { num: "4", title: "Songwriter Warranties", text: "Songwriter warrants: (i) sole ownership of the publisher share being assigned; (ii) the Composition is original; (iii) no samples or interpolations save those disclosed in Schedule A; (iv) no third-party rights are infringed; (v) no prior assignment of the publisher share." },
  { num: "5", title: "Writer Share", text: "Nothing in this Agreement assigns or affects Songwriter's writer share. Performance income from the writer share is collected by Songwriter's PRO direct and is not part of this assignment." },
  { num: "6", title: "Reversion", text: "Where Schedule A grants a reversion right, the assignment shall revert to Songwriter on the terms specified (typically 7-10 years post-effective date, conditional on full recoupment of any advance). Reversion shall be effected by execution of a deed of reversion and registration with the relevant PROs and MROs." },
  { num: "7", title: "Indemnity", text: "Songwriter indemnifies Publisher against direct claims arising from breach of warranties up to a cap equal to amounts paid under this Agreement." },
  { num: "8", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];
