/**
 * Shared clause libraries for the A&R/Recording module's contracts.
 * Centralised so updates can be made in one place — pages render via
 * the ResourcePage + ClauseAccordion pattern.
 */
export interface Clause { num: string; title: string; text: string; }

export const STUDIO_BOOKING = (govLaw: string): Clause[] => [
  { num: "1", title: "Booking & Lockout", text: "Studio confirms booking of the room(s) and dates set out in Schedule A on a lockout basis (no other client during the booked hours). Booking is firm on payment of the deposit. Hours may be extended on the day at the prevailing hourly rate, subject to availability." },
  { num: "2", title: "Rates & Payment", text: "Day / hour rates and the engineer / runner / consumables charges are set out in Schedule A. Deposit of 50% is due on booking; balance is due on or before the first day. Out-of-hours and public-holiday surcharges shall apply only as specified in Schedule A. Cancellation: full refund 14+ days before; 50% within 7 days; no refund within 48 hours." },
  { num: "3", title: "Engineer", text: "Where Studio supplies an engineer, the engineer is engaged through Studio and shall act under the producer's direction. The engineer's hours are part of the day rate unless Schedule A specifies overtime. Studio shall not represent that the engineer is a co-producer or is entitled to royalty income." },
  { num: "4", title: "Multitracks & Project Files", text: "All multitracks, session files, comps, plug-in settings and bounces created during the booking belong to the Client. Studio shall deliver project files and stems on hand-off media at the end of the booking. Studio may retain backup copies for archival purposes for up to twelve (12) months only." },
  { num: "5", title: "Equipment & Damage", text: "Client and accompanying personnel shall not bring in unauthorised equipment without Studio's prior consent. Damage to Studio equipment or premises caused by Client or Client's guests shall be charged at replacement cost, supported by an itemised invoice. Studio carries equipment and public liability insurance for ordinary use." },
  { num: "6", title: "Conduct", text: "No unauthorised photography in the live room. No food or drink on consoles or in vocal booths. Substance use is governed by Studio's house rules; failure to comply may result in termination of the booking with no refund. Studio reserves the right to remove any guest causing disruption." },
  { num: "7", title: "Privacy", text: "Studio shall keep confidential the identity of artists working in the booked room and any material recorded. No social media, public statements or guest lists shall be issued without Client's prior written consent." },
  { num: "8", title: "Force Majeure", text: "Where the booking cannot proceed due to power outage exceeding two (2) hours, equipment failure, or force majeure event, Studio shall offer like-for-like make-up time at the next available date or refund pro-rata." },
  { num: "9", title: "Liability", text: "Studio's liability for any claim arising from the booking (other than personal injury caused by Studio's negligence) is limited to the fees paid for the booking. Client carries its own insurance for personal property brought into the Studio." },
  { num: "10", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Disputes shall be resolved by mediation and, failing resolution, by arbitration in the country of governance.` },
];

export const MIXING_ENGINEER = (govLaw: string): Clause[] => [
  { num: "1", title: "Engagement", text: "Engineer is engaged to mix the Master Recording(s) listed in Schedule A. Mix shall be delivered as a stereo 24-bit/48 kHz WAV (or higher), with stems (drums, bass, vocals, instruments, FX, master bus) where Schedule A so specifies." },
  { num: "2", title: "Fee & Revisions", text: "Per-mix fee is set out in Schedule A and is due 50% on commencement and 50% on delivery. Fee includes two (2) revision rounds at no additional cost. Further revisions are billable at the per-revision rate in Schedule A. Fee is exclusive of VAT (where applicable)." },
  { num: "3", title: "Deliverables & Format", text: "Engineer shall deliver: (i) stereo mix at the highest fidelity captured; (ii) instrumental version; (iii) acapella; (iv) TV mix; (v) all stems if Schedule A so specifies. Deliverables are uploaded to a Client-owned cloud folder or hand-off drive — not the engineer's drive." },
  { num: "4", title: "Ownership of Mix", text: "All right, title and interest in the mix and all underlying session files vest in Client (or Client's loan-out / label) on payment of the final fee. Engineer retains no copyright, royalty, points, or other ongoing economic interest in the recording. Engineer is acknowledged in liner-note / streaming credits." },
  { num: "5", title: "Mixing Credit", text: "Client shall accord Engineer credit substantially as: \"Mixed by [Engineer Name].\" Credit shall appear in distributor metadata where the field is available, on physical packaging, and on the artist's electronic press kit. Inadvertent credit error shall be remedied for prospective uploads on notice." },
  { num: "6", title: "Independent Contractor", text: "Engineer provides services as an independent contractor and is responsible for own tax, retirement and insurance. Engineer is not entitled to PAYE deduction, leave, or other employee benefits." },
  { num: "7", title: "Warranties", text: "Engineer warrants competence to perform the services to industry standard and that no third-party rights are infringed in the course of mixing. Where Engineer uses sample libraries / drum kits, Engineer warrants that the licence permits commercial release." },
  { num: "8", title: "Confidentiality", text: "Engineer shall not disclose, share, post, upload or play to third parties any unreleased material received under this Agreement. Posting WIPs or behind-the-scenes content requires Client's prior written consent." },
  { num: "9", title: "Termination", text: "Either party may terminate on seven (7) days' notice for material breach not cured. On termination Engineer shall return all session files and is entitled to fees due for work performed up to termination." },
  { num: "10", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Disputes shall be resolved by mediation and, failing resolution, by arbitration in the country of governance.` },
];

export const MASTERING_ENGINEER = (govLaw: string): Clause[] => [
  { num: "1", title: "Engagement", text: "Engineer is engaged to master the recording(s) set out in Schedule A. Mastering deliverables shall include: (i) DDP image for physical replication (where ordered); (ii) high-resolution streaming master (24-bit / 48-96 kHz); (iii) Apple Digital Master-encoded version; (iv) loudness-normalised reference (LUFS Integrated −14 / −10 / −9 per platform target); (v) MFiT and Atmos masters where ordered separately." },
  { num: "2", title: "Fee", text: "Per-track or per-album fee is set out in Schedule A. 50% on commencement, 50% on delivery. Includes one revision round; further revisions are billable. Atmos / Spatial mastering is a separate scope and a separate fee." },
  { num: "3", title: "Loudness & Specifications", text: "Engineer shall master to the platform-appropriate loudness target. Engineer shall not exceed −1 dBTP true peak unless Client approves a specific creative reason in writing. Apple Digital Master compliance includes adherence to MFiT specifications including no clipping at the encoded format." },
  { num: "4", title: "Ownership of Master", text: "All right, title and interest in the mastered files vest in Client on payment of the final fee. Engineer retains no royalty, point or other ongoing interest. Engineer is credited substantially as: \"Mastered by [Engineer Name].\"" },
  { num: "5", title: "Reference Lab Conditions", text: "Engineer warrants that mastering takes place in a treated, calibrated mastering room with reference monitors and that meter readings reported to Client are accurate. Engineer shall not use AI / preset-only mastering services without Client's express consent." },
  { num: "6", title: "Stems & Recall", text: "Engineer shall retain settings and project files for not less than ninety (90) days post-delivery for recall on Client's request. Recall after 90 days is billable at the recall rate in Schedule A." },
  { num: "7", title: "Independent Contractor", text: "Engineer is an independent contractor responsible for own tax and statutory obligations." },
  { num: "8", title: "Confidentiality", text: "Engineer shall not share, post, or play unreleased mastered files. Reference samples for marketing of Engineer's services require written consent." },
  { num: "9", title: "Liability", text: "Engineer's liability is capped at the fees paid for the engagement save for fraud or wilful misconduct." },
  { num: "10", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}.` },
];

export const FEATURED_ARTIST = (govLaw: string, lawyerNote: string): Clause[] => [
  { num: "1", title: "Engagement", text: "Featured Artist is engaged to record a guest performance on the recording(s) listed in Schedule A. Featured Artist's performance shall be original, recorded to a quality acceptable for commercial release, and delivered by the date set out in Schedule A." },
  { num: "2", title: "Compensation", text: "Featured Artist shall receive: (i) a flat performance fee as set out in Schedule A; or (ii) a master royalty point share as set out in Schedule A; or (iii) a combination of both, as agreed. Where the engagement involves a publishing share, Featured Artist's writer credit is set out in Schedule B and registered separately with the relevant PROs." },
  { num: "3", title: "Master Ownership", text: "Featured Artist's vocal and any incidental contribution embodied in the master shall be owned by the commissioning party (Lead Artist or Label). Featured Artist's economic interest is limited to the fee and royalty points (if any) set out in Schedule A. Featured Artist shall not be entitled to administer or sub-licence the master." },
  { num: "4", title: "Compositional Rights", text: "Where Featured Artist contributes lyrics, melody or topline, Featured Artist's writer/publisher share shall be confirmed in writing in a Co-Writing Splits Agreement before the recording is finalised. Splits shall be registered with the relevant PROs (SAMRO/COSON/etc.) by Featured Artist within thirty (30) days of agreement." },
  { num: "5", title: "Side-Artist Approval (Label-signed)", text: "Where Featured Artist is signed to a third-party record label, Featured Artist warrants that label approval has been obtained or that Featured Artist will procure such approval within fourteen (14) days. Lead Artist may, at Lead Artist's option, withhold release pending receipt of a Side-Artist Letter of Direction from Featured Artist's label." },
  { num: "6", title: "Credit", text: "Featured Artist shall be credited substantially as: \"[Track] (feat. [Featured Artist])\" on all DSP metadata, physical packaging, video credits and marketing material. Failure to credit is a material breach (subject to inadvertent / correctable error provision)." },
  { num: "7", title: "Promotion & Likeness", text: "Featured Artist grants Lead Artist a non-exclusive worldwide perpetual licence to use Featured Artist's name, likeness, image and biographical information in marketing the track and any associated music video, in formats and channels customary in the music industry. Featured Artist's image rights for endorsements and brand campaigns are reserved." },
  { num: "8", title: "Music Video & Performance", text: "Featured Artist shall make reasonable efforts to attend a music video shoot at a mutually agreed date, with travel, accommodation and per-diem at Lead Artist's cost. Where Featured Artist is unavailable, Lead Artist may proceed without Featured Artist's appearance." },
  { num: "9", title: "Sample / Sample Replay Clearance", text: "Lead Artist warrants that all sample clearances on the recording have been or will be obtained at Lead Artist's cost prior to release. Featured Artist's contribution shall not be liable for sample-clearance costs save where the sample was introduced by Featured Artist." },
  { num: "10", title: "Royalties Accounting (where applicable)", text: "Where royalty points apply, Lead Artist shall account to Featured Artist on a semi-annual basis (30 June / 31 December) and shall remit royalties due within thirty (30) days of period end, with statement detail showing streams, downloads, sync income, and direct deductions if any." },
  { num: "11", title: "Warranties", text: "Featured Artist warrants the right to perform, that no exclusive recording agreement bars the contribution (subject to clause 5), and that no third-party rights are infringed. Lead Artist indemnifies Featured Artist against the underlying composition's clearance status; Featured Artist indemnifies Lead Artist against the contribution's status." },
  { num: "12", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}. Each party shall, before signing, consult ${lawyerNote}.` },
];

export const BEAT_LEASE = (govLaw: string): Clause[] => [
  { num: "1", title: "Grant", text: "Producer grants Buyer the right to use the beat / instrumental identified in Schedule A for the licence type stated (Non-Exclusive Lease / Premium Lease / Exclusive Buyout). Rights granted vary by licence type and are set out in Schedule B." },
  { num: "2", title: "Non-Exclusive Lease", text: "Where stated, Producer grants Buyer a non-exclusive perpetual licence to release the beat as part of one (1) recording. Producer retains the right to license the beat to other buyers. Streaming and download cap is fifty thousand (50,000) units. Live performance is permitted. Music video is permitted with on-screen producer tag." },
  { num: "3", title: "Premium Lease", text: "Where stated, Producer grants Buyer a non-exclusive perpetual licence with: streaming and download cap of five hundred thousand (500,000) units; unlimited live performance; one (1) music video; one (1) commercial / sync use. Producer retains the right to license to other buyers but at a higher base rate than Non-Exclusive." },
  { num: "4", title: "Exclusive Buyout", text: "Where stated, Producer transfers exclusive master ownership of the beat to Buyer with no streaming cap, all media, world. Producer retains writer share of any composition embodied in the beat (typically 50%) and shall be registered with the relevant PROs accordingly. Producer shall not licence the beat to any further party from the date of buyout." },
  { num: "5", title: "Producer Credit", text: "Buyer shall credit Producer in distributor metadata, video credits and any tagged release material substantially as: \"Produced by [Producer Name].\" Producer's PRO affiliation shall be identified in writer metadata where applicable." },
  { num: "6", title: "Fee", text: "Fee is set out in Schedule A and is payable in full prior to release. No royalty share is payable on Non-Exclusive or Premium Lease releases save where Producer's writer share generates back-end performance income through PROs. On Exclusive Buyout, the fee is the entire consideration save for back-end PRO income." },
  { num: "7", title: "Sample-Cleared Beats", text: "Producer warrants that the beat is original and free of uncleared samples save where disclosed in Schedule A. Where samples are present and not yet cleared, the licence is conditional on Buyer or Producer (as agreed) clearing the underlying material. The cost of sample clearance is allocated as set out in Schedule A." },
  { num: "8", title: "Tag Removal", text: "Producer shall provide a tag-free version of the beat on payment of the fee. Tagged versions shall not be released commercially under any licence type." },
  { num: "9", title: "Compositions", text: "Producer retains writer share of any compositional element of the beat (melody, chord progression, topline if any). Buyer's lyrics and vocal melody are Buyer's compositional contribution. Splits between Producer and Buyer are agreed in writing using the Co-Writing Splits Agreement before release." },
  { num: "10", title: "Termination & Caps", text: "Where Buyer exceeds the streaming/download cap of a Lease licence, Buyer shall upgrade to Premium or Exclusive at the prevailing rate. Failure to upgrade within thirty (30) days of notice constitutes a material breach permitting Producer to issue a takedown." },
  { num: "11", title: "Governing Law", text: `This Agreement is governed by the laws of ${govLaw}.` },
];
