/**
 * VAT registration thresholds across the 15 IFPI key African markets.
 * Used by /money/vat-decision to tell artists whether they should register.
 *
 * Last reviewed: April 2026. Confirm with the local authority before acting.
 */
export interface VatThreshold {
  country: string;
  authority: string;
  taxName: string;
  rate: number;                    // standard rate (whole number, e.g. 15)
  thresholdLocal: number;          // turnover threshold in local currency
  thresholdLocalLabel: string;     // human-readable e.g. "ZAR 1,000,000"
  currency: string;
  period: "12 months rolling" | "Calendar year" | "Fiscal year";
  voluntaryFrom: string | null;    // voluntary registration floor
  reclaimable: boolean;            // can input VAT be claimed back?
  cadence: string;                 // "Monthly" / "Bi-monthly" / etc.
  notes: string;
  authorityUrl: string;
}

export const VAT_THRESHOLDS: Record<string, VatThreshold> = {
  "South Africa": {
    country: "South Africa",
    authority: "SARS",
    taxName: "VAT",
    rate: 15,
    thresholdLocal: 1_000_000,
    thresholdLocalLabel: "ZAR 1,000,000",
    currency: "ZAR",
    period: "12 months rolling",
    voluntaryFrom: "ZAR 50,000",
    reclaimable: true,
    cadence: "Bi-monthly (Cat. B for most musicians)",
    notes: "Compulsory registration once trailing 12-month turnover exceeds R1m. Voluntary registration possible from R50k turnover. VAT201 form via eFiling.",
    authorityUrl: "https://www.sars.gov.za/types-of-tax/value-added-tax/",
  },
  "Nigeria": {
    country: "Nigeria",
    authority: "FIRS",
    taxName: "VAT",
    rate: 7.5,
    thresholdLocal: 25_000_000,
    thresholdLocalLabel: "NGN 25,000,000",
    currency: "NGN",
    period: "Calendar year",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly (by 21st)",
    notes: "Small companies under NGN 25m turnover are exempt under the Finance Act 2020. Above threshold: file monthly via TaxPro Max.",
    authorityUrl: "https://firs.gov.ng/value-added-tax/",
  },
  "Ghana": {
    country: "Ghana",
    authority: "GRA",
    taxName: "VAT (+ NHIL + GETFund + COVID)",
    rate: 15,
    thresholdLocal: 200_000,
    thresholdLocalLabel: "GHS 200,000",
    currency: "GHS",
    period: "12 months rolling",
    voluntaryFrom: "Below threshold",
    reclaimable: true,
    cadence: "Monthly",
    notes: "Compulsory at GHS 200,000. Combined effective rate ~21% incl. 2.5% NHIL + 2.5% GETFund + 1% COVID-19 levy. Filed via GRA E-Services.",
    authorityUrl: "https://gra.gov.gh/",
  },
  "Kenya": {
    country: "Kenya",
    authority: "KRA",
    taxName: "VAT",
    rate: 16,
    thresholdLocal: 5_000_000,
    thresholdLocalLabel: "KES 5,000,000",
    currency: "KES",
    period: "12 months rolling",
    voluntaryFrom: "Below threshold (KRA approval)",
    reclaimable: true,
    cadence: "Monthly (by 20th)",
    notes: "Compulsory at KES 5m trailing 12-month turnover. VAT3 form via iTax. Some music services may qualify for exempt / zero-rated treatment — check Schedule.",
    authorityUrl: "https://www.kra.go.ke/individual/filing-paying/types-of-taxes/value-added-tax",
  },
  "Egypt": {
    country: "Egypt",
    authority: "ETA (Egyptian Tax Authority)",
    taxName: "VAT",
    rate: 14,
    thresholdLocal: 500_000,
    thresholdLocalLabel: "EGP 500,000",
    currency: "EGP",
    period: "12 months rolling",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly",
    notes: "Compulsory at EGP 500k turnover. Reduced 10% rate for some services. Filed online via ETA portal.",
    authorityUrl: "https://www.eta.gov.eg/",
  },
  "Ethiopia": {
    country: "Ethiopia",
    authority: "MOR (Ministry of Revenues)",
    taxName: "VAT",
    rate: 15,
    thresholdLocal: 1_000_000,
    thresholdLocalLabel: "ETB 1,000,000",
    currency: "ETB",
    period: "12 months rolling",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly",
    notes: "Compulsory at ETB 1m turnover. Filed via MOR e-Tax. Below threshold: TOT (Turnover Tax) at 2% applies instead.",
    authorityUrl: "https://www.mor.gov.et/",
  },
  "Morocco": {
    country: "Morocco",
    authority: "DGI",
    taxName: "TVA",
    rate: 20,
    thresholdLocal: 1_000_000,
    thresholdLocalLabel: "MAD 1,000,000",
    currency: "MAD",
    period: "Calendar year",
    voluntaryFrom: "Below threshold",
    reclaimable: true,
    cadence: "Monthly (mandatory above MAD 1m)",
    notes: "Above MAD 1m: monthly. Below: quarterly. Voluntary registration possible via SIMPL-TVA.",
    authorityUrl: "https://www.tax.gov.ma/",
  },
  "Algeria": {
    country: "Algeria",
    authority: "DGI",
    taxName: "TVA",
    rate: 19,
    thresholdLocal: 8_000_000,
    thresholdLocalLabel: "DZD 8,000,000 (real-regime)",
    currency: "DZD",
    period: "Calendar year",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly (G50 form, by 20th)",
    notes: "Real-regime taxpayers (above DZD 8m) charge / reclaim TVA. Below threshold: IFU flat tax 5–12% applies, no VAT.",
    authorityUrl: "https://www.mfdgi.gov.dz/",
  },
  "Côte d'Ivoire": {
    country: "Côte d'Ivoire",
    authority: "DGI",
    taxName: "TVA",
    rate: 18,
    thresholdLocal: 50_000_000,
    thresholdLocalLabel: "XOF 50,000,000 (services)",
    currency: "XOF",
    period: "Calendar year",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly (by 15th private / 10th public)",
    notes: "XOF 50m for services / XOF 200m for goods. Below threshold: simplified regime. Filed via e-Impôts.",
    authorityUrl: "https://www.impots.gouv.ci/",
  },
  "Cameroon": {
    country: "Cameroon",
    authority: "DGI",
    taxName: "TVA (+ 10% CAC)",
    rate: 19.25,
    thresholdLocal: 50_000_000,
    thresholdLocalLabel: "XAF 50,000,000",
    currency: "XAF",
    period: "Calendar year",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly (by 15th)",
    notes: "Combined 19.25% (incl. 10% Communal Tax). Compulsory at XAF 50m turnover.",
    authorityUrl: "https://impots.cm/",
  },
  "Tanzania": {
    country: "Tanzania",
    authority: "TRA",
    taxName: "VAT",
    rate: 18,
    thresholdLocal: 200_000_000,
    thresholdLocalLabel: "TZS 200,000,000",
    currency: "TZS",
    period: "12 months rolling",
    voluntaryFrom: "Below threshold (TRA approval)",
    reclaimable: true,
    cadence: "Monthly (by 20th)",
    notes: "Compulsory at TZS 200m. Filed via TRA online portal. Voluntary registration available below threshold.",
    authorityUrl: "https://www.tra.go.tz/",
  },
  "Senegal": {
    country: "Senegal",
    authority: "DGID",
    taxName: "TVA",
    rate: 18,
    thresholdLocal: 50_000_000,
    thresholdLocalLabel: "XOF 50,000,000 (services)",
    currency: "XOF",
    period: "Calendar year",
    voluntaryFrom: null,
    reclaimable: true,
    cadence: "Monthly (by 15th)",
    notes: "XOF 50m services / 100m goods. Filed via DGID e-Tax.",
    authorityUrl: "https://www.impotsetdomaines.gouv.sn/",
  },
  "Angola": {
    country: "Angola",
    authority: "AGT (Administração Geral Tributária)",
    taxName: "IVA",
    rate: 14,
    thresholdLocal: 350_000_000,
    thresholdLocalLabel: "AOA 350,000,000",
    currency: "AOA",
    period: "Calendar year",
    voluntaryFrom: "Below threshold",
    reclaimable: true,
    cadence: "Monthly (or quarterly under simplified)",
    notes: "Compulsory at AOA 350m. Simplified regime available below. Filed via e-Fatura.",
    authorityUrl: "https://www.agt.minfin.gov.ao/",
  },
  "Uganda": {
    country: "Uganda",
    authority: "URA",
    taxName: "VAT",
    rate: 18,
    thresholdLocal: 150_000_000,
    thresholdLocalLabel: "UGX 150,000,000",
    currency: "UGX",
    period: "12 months rolling",
    voluntaryFrom: "Below threshold (URA approval)",
    reclaimable: true,
    cadence: "Monthly (by 15th)",
    notes: "Compulsory at UGX 150m. Voluntary registration possible. Filed via URA e-Tax.",
    authorityUrl: "https://www.ura.go.ug/",
  },
  "Zimbabwe": {
    country: "Zimbabwe",
    authority: "ZIMRA",
    taxName: "VAT",
    rate: 15,
    thresholdLocal: 25_000,
    thresholdLocalLabel: "USD 25,000",
    currency: "USD",
    period: "12 months rolling",
    voluntaryFrom: "Below threshold",
    reclaimable: true,
    cadence: "Monthly (by 25th)",
    notes: "Compulsory at USD 25,000 trailing 12-month turnover. ZIMRA threshold is USD-pegged. Filed via ZIMRA e-Services.",
    authorityUrl: "https://www.zimra.co.zw/",
  },
};

export const VAT_COUNTRIES = Object.keys(VAT_THRESHOLDS);
